package lab6_miguelrojas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class Main_Lab6 extends javax.swing.JFrame {

    public Main_Lab6() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearSerVivo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreSerVivo = new javax.swing.JTextField();
        js_poderSerVivo = new javax.swing.JSpinner();
        tf_añosSerVivo = new javax.swing.JTextField();
        tf_planetaSerVivo = new javax.swing.JTextField();
        rb_Humano = new javax.swing.JRadioButton();
        rb_Amanto = new javax.swing.JRadioButton();
        jb_CrearSerVivo = new javax.swing.JButton();
        bg_RazaSerVivo = new javax.swing.ButtonGroup();
        jd_menuUniversos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jb_crearUniverso = new javax.swing.JButton();
        jb_regresarMain = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaUniversos = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jb_modificarSerVivo = new javax.swing.JButton();
        jb_EliminarSerVivo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jb_agregarSerVivo = new javax.swing.JButton();
        cb_universos = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jd_modSerVivo = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombreSerVivoMod = new javax.swing.JTextField();
        js_poderSerVivoMod = new javax.swing.JSpinner();
        tf_añosSerVivoMod = new javax.swing.JTextField();
        tf_planetaSerVivoMod = new javax.swing.JTextField();
        rb_AmantoMod = new javax.swing.JRadioButton();
        rb_HumanoMod = new javax.swing.JRadioButton();
        jb_modSerVivo = new javax.swing.JButton();
        bg_RazaMod = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jb_cargarArchivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_Archivos = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jb_menuUniversos = new javax.swing.JButton();
        jb_guardarUniverso = new javax.swing.JButton();

        jd_CrearSerVivo.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Crear Ser Vivo");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Poder:");

        jLabel5.setText("Años:");

        jLabel6.setText("Planeta:");

        jLabel7.setText("Raza:");

        js_poderSerVivo.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        bg_RazaSerVivo.add(rb_Humano);
        rb_Humano.setSelected(true);
        rb_Humano.setText("Humano");

        bg_RazaSerVivo.add(rb_Amanto);
        rb_Amanto.setText("Amanto");

        jb_CrearSerVivo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jb_CrearSerVivo.setText("Crear");
        jb_CrearSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearSerVivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearSerVivoLayout = new javax.swing.GroupLayout(jd_CrearSerVivo.getContentPane());
        jd_CrearSerVivo.getContentPane().setLayout(jd_CrearSerVivoLayout);
        jd_CrearSerVivoLayout.setHorizontalGroup(
            jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                        .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_poderSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_planetaSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(37, 37, 37)
                                        .addComponent(rb_Humano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_Amanto)
                                        .addGap(0, 55, Short.MAX_VALUE))))
                            .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                                .addComponent(tf_añosSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearSerVivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_CrearSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jd_CrearSerVivoLayout.setVerticalGroup(
            jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearSerVivoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_planetaSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(js_poderSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_Humano)
                    .addComponent(rb_Amanto))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_añosSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_CrearSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        jd_menuUniversos.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentHidden(evt);
            }
        });

        jb_crearUniverso.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jb_crearUniverso.setText("Crear Universo");
        jb_crearUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearUniversoMouseClicked(evt);
            }
        });

        jb_regresarMain.setText("Regresar a Main");
        jb_regresarMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarMainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jb_crearUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jb_regresarMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jb_crearUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jb_regresarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Crear Universo", jPanel2);

        jScrollPane1.setViewportView(jl_listaUniversos);

        jLabel8.setText("Lista de Universos");

        jb_modificarSerVivo.setText("Modificar Ser Vivo");
        jb_modificarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarSerVivoMouseClicked(evt);
            }
        });

        jb_EliminarSerVivo.setText("Eliminar Ser Vivo");
        jb_EliminarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarSerVivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_modificarSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_EliminarSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jb_modificarSerVivo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_EliminarSerVivo)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar/Eliminar", jPanel3);

        jb_agregarSerVivo.setText("Agregar Ser Vivo");
        jb_agregarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarSerVivoMouseClicked(evt);
            }
        });

        jLabel15.setText("Universos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cb_universos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jb_agregarSerVivo)
                .addGap(167, 167, 167))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(cb_universos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_agregarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Ser Vivo", jPanel4);

        javax.swing.GroupLayout jd_menuUniversosLayout = new javax.swing.GroupLayout(jd_menuUniversos.getContentPane());
        jd_menuUniversos.getContentPane().setLayout(jd_menuUniversosLayout);
        jd_menuUniversosLayout.setHorizontalGroup(
            jd_menuUniversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuUniversosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18))
        );
        jd_menuUniversosLayout.setVerticalGroup(
            jd_menuUniversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuUniversosLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel14.setText("Modificar");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Poder:");

        jLabel11.setText("Años:");

        jLabel12.setText("Planeta:");

        jLabel13.setText("Raza:");

        js_poderSerVivoMod.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        bg_RazaMod.add(rb_AmantoMod);
        rb_AmantoMod.setText("Amanto");

        bg_RazaMod.add(rb_HumanoMod);
        rb_HumanoMod.setSelected(true);
        rb_HumanoMod.setText("Humano");

        jb_modSerVivo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jb_modSerVivo.setText("Modificar");
        jb_modSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modSerVivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modSerVivoLayout = new javax.swing.GroupLayout(jd_modSerVivo.getContentPane());
        jd_modSerVivo.getContentPane().setLayout(jd_modSerVivoLayout);
        jd_modSerVivoLayout.setHorizontalGroup(
            jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                        .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                                .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_poderSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_añosSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_planetaSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(37, 37, 37)
                                        .addComponent(rb_HumanoMod)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_AmantoMod)
                                        .addContainerGap(55, Short.MAX_VALUE))))
                            .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jb_modSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))))
                    .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap())))
        );
        jd_modSerVivoLayout.setVerticalGroup(
            jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modSerVivoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(tf_nombreSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_planetaSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(js_poderSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_HumanoMod)
                            .addComponent(rb_AmantoMod))
                        .addGap(34, 34, 34)
                        .addGroup(jd_modSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_añosSerVivoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modSerVivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_modSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_cargarArchivo.setText("Cargar Universo");
        jb_cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cargarArchivoMouseClicked(evt);
            }
        });

        ta_Archivos.setColumns(20);
        ta_Archivos.setRows(5);
        jScrollPane2.setViewportView(ta_Archivos);

        jLabel16.setText("Informacion Cargada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jb_cargarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jb_cargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Lab6_Miguel Rojas");

        jb_menuUniversos.setText("Menu Universos");
        jb_menuUniversos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_menuUniversosMouseClicked(evt);
            }
        });

        jb_guardarUniverso.setText("Guardar Universo");
        jb_guardarUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarUniversoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_menuUniversos)
                        .addGap(135, 135, 135)
                        .addComponent(jb_guardarUniverso))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_menuUniversos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_guardarUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_CrearSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearSerVivoMouseClicked
        //Accion Crear Ser Vivo

        boolean crear = true;
        String nombre = null, planeta = null, raza = null;
        int poder = 0, years = 0;

        //Validar Entradas de Datos
        //Nombre
        if (tf_nombreSerVivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_CrearSerVivo, "Falta ingresar el nombre del ser vivo");
            crear = false;
        } else {
            nombre = tf_nombreSerVivo.getText();
        }

        //Poder
        if ((int) js_poderSerVivo.getValue() < 1) {
            JOptionPane.showMessageDialog(jd_CrearSerVivo, "El valor de poder no puede ser menor a 1.");
            crear = false;
        } else if ((int) js_poderSerVivo.getValue() > 10) {
            JOptionPane.showMessageDialog(jd_CrearSerVivo, "El valor de poder no puede ser mayor a 10.");
            crear = false;
        } else {
            poder = (int) js_poderSerVivo.getValue();
        }

        //Años
        if (tf_añosSerVivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_CrearSerVivo, "Falta ingresar los años del ser vivo.");
            crear = false;
        } else {
            years = Integer.parseInt(tf_añosSerVivo.getText());
        }

        //Planeta
        if (tf_planetaSerVivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_CrearSerVivo, "Falta ingresar el planeta de procedencia del ser vivo.");
            crear = false;
        } else {
            planeta = tf_planetaSerVivo.getText();
        }

        //Raza
        if (rb_Humano.isSelected()) {
            raza = "Humano";
        } else {
            raza = "Amanto";
        }

        //Entradas Validadas
        if (crear) {
            try {
                //Crear Objeto
                Seres_Vivos sv = new Seres_Vivos(nombre, poder, years, planeta, raza);
                u_seleccionado.setSerVivo(sv);
                //Crear Text File
                if (u_seleccionado.getArchivo() != null) {
                    try {
                        u_seleccionado.escribirArchivo(u_seleccionado.getArchivo().toString());
                    } catch (IOException ex) {

                    }
                }

                JOptionPane.showMessageDialog(jd_CrearSerVivo, "Se creo exitosamente el ser vivo y se logro agregar al universo!!");
                
                if (ciclo == 0) {
                    int resp_seguir = JOptionPane.showConfirmDialog(this, "¿Desea agregar otro ser vivo?", "Crear Ser Vivo",
                            JOptionPane.YES_NO_OPTION);

                    if (resp_seguir == 0) {
                        //Agregara otro ser
                        tf_nombreSerVivo.setText("");
                        js_poderSerVivo.setValue(0);
                        tf_añosSerVivo.setText("");
                        tf_planetaSerVivo.setText("");
                        rb_Humano.setSelected(true);
                        rb_Amanto.setSelected(false);

                    } else {
                        //Limpiar Entradas
                        tf_nombreSerVivo.setText("");
                        js_poderSerVivo.setValue(0);
                        tf_añosSerVivo.setText("");
                        tf_planetaSerVivo.setText("");
                        rb_Humano.setSelected(true);
                        rb_Amanto.setSelected(false);
                        jd_CrearSerVivo.dispose();
                        jd_menuUniversos.setVisible(true);
                    }
                } else {
                    tf_nombreSerVivo.setText("");
                    js_poderSerVivo.setValue(0);
                    tf_añosSerVivo.setText("");
                    tf_planetaSerVivo.setText("");
                    rb_Humano.setSelected(true);
                    rb_Amanto.setSelected(false);
                    jd_CrearSerVivo.dispose();
                    jd_menuUniversos.setVisible(true);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jb_CrearSerVivoMouseClicked

    private void jb_menuUniversosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_menuUniversosMouseClicked
        //Accion abrir menu Universos
        this.setVisible(false);
        jd_menuUniversos.setModal(true);
        jd_menuUniversos.pack();
        jd_menuUniversos.setLocationRelativeTo(this);
        jd_menuUniversos.setVisible(true);
    }//GEN-LAST:event_jb_menuUniversosMouseClicked

    private void jb_crearUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearUniversoMouseClicked
        //Accion crear Universo
        String nombre_universo = JOptionPane.showInputDialog(jd_menuUniversos, "Ingrese nombre de Universo",
                "Crear Universo", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(jd_menuUniversos, "Universo creado exitosamente!!\n"
                + "Ahora cree algun ser vivo.");

        Universo u = new Universo(nombre_universo);
        listaUniversos.add(u);

        //Agregar universo a Lista
        refrescarListaUniversos();
        refrescarCBUniversos();
        //Conseguir objeto de universo creado
        u_seleccionado = u;
        jd_menuUniversos.setVisible(false);
        jd_CrearSerVivo.setModal(true);
        jd_CrearSerVivo.pack();
        jd_CrearSerVivo.setLocationRelativeTo(jd_menuUniversos);
        jd_CrearSerVivo.setVisible(true);
    }//GEN-LAST:event_jb_crearUniversoMouseClicked

    private void jb_modificarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarSerVivoMouseClicked

        if (jl_listaUniversos.getSelectedIndex() >= 0) {
            u_seleccionado = listaUniversos.get(jl_listaUniversos.getSelectedIndex());

            String salida_seresVivos = "";
            for (int i = 0; i < u_seleccionado.getLista_seresVivos().size(); i++) {
                salida_seresVivos += "[" + i + "]" + u_seleccionado.getLista_seresVivos().get(i) + "\n";
            }

            int opcion_mod = Integer.parseInt(JOptionPane.showInputDialog(jd_menuUniversos, "Lista de Seres Vivos del Univero "
                    + u_seleccionado.getNombre() + "\n" + salida_seresVivos + "\nEliga ser vivo a modificar: "));

            Seres_Vivos sv_mod = u_seleccionado.getSerVivo(opcion_mod);
            sv_seleccionado = sv_mod;
            //Asignar Valores
            tf_nombreSerVivoMod.setText(sv_mod.getNombre());
            js_poderSerVivoMod.setValue((int) sv_mod.getPoder());
            tf_añosSerVivoMod.setText(Integer.toString(sv_mod.getYears()));
            tf_planetaSerVivoMod.setText(sv_mod.getPlaneta_procedencia());
            if (sv_mod.getRaza().equals("Humano")) {
                rb_HumanoMod.setSelected(true);
                rb_AmantoMod.setSelected(false);
            } else {
                rb_HumanoMod.setSelected(false);
                rb_AmantoMod.setSelected(true);
            }

            //Abrir Ventana de Modificacion
            jd_menuUniversos.setVisible(false);
            jd_modSerVivo.setModal(true);
            jd_modSerVivo.pack();
            jd_modSerVivo.setLocationRelativeTo(jd_menuUniversos);
            jd_modSerVivo.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(jd_menuUniversos, "Debe elegir un Universo.");
        }
    }//GEN-LAST:event_jb_modificarSerVivoMouseClicked

    private void jb_modSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modSerVivoMouseClicked
        //Acion de Modificar Ser Vivo

        //Validar
        boolean mod = true;

        //Validar Entradas de Datos
        //Nombre
        if (tf_nombreSerVivoMod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modSerVivo, "Falta ingresar el nombre del ser vivo");
            mod = false;
        }
        //Poder
        if ((int) js_poderSerVivoMod.getValue() < 1) {
            JOptionPane.showMessageDialog(jd_modSerVivo, "El valor de poder no puede ser menor a 1.");
            mod = false;
        } else if ((int) js_poderSerVivoMod.getValue() > 10) {
            JOptionPane.showMessageDialog(jd_modSerVivo, "El valor de poder no puede ser mayor a 10.");
            mod = false;
        }

        //Años
        if (tf_añosSerVivoMod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modSerVivo, "Falta ingresar los años del ser vivo.");
            mod = false;
        }

        //Planeta
        if (tf_planetaSerVivoMod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_modSerVivo, "Falta ingresar el planeta de procedencia del ser vivo.");
            mod = false;
        }

        if (mod) {
            try {
                sv_seleccionado.setNombre(tf_nombreSerVivoMod.getText());
                sv_seleccionado.setPoder((int) js_poderSerVivoMod.getValue());
                sv_seleccionado.setYears(Integer.parseInt(tf_añosSerVivoMod.getText()));
                sv_seleccionado.setPlaneta_procedencia(tf_planetaSerVivoMod.getText());
                //Raza
                if (rb_HumanoMod.isSelected()) {
                    sv_seleccionado.setRaza("Humano");
                } else {
                    sv_seleccionado.setRaza("Amanto");
                }
                if (u_seleccionado.getArchivo() != null) {
                    try {
                        u_seleccionado.escribirArchivo(u_seleccionado.getArchivo().toString());
                    } catch (IOException ex) {

                    }
                }

                JOptionPane.showMessageDialog(jd_modSerVivo, "Se modifico exitosamente el ser vivo");
                //escribir archivo
                //u_seleccionado.escribirArchivo();
                jd_modSerVivo.dispose();
                jd_menuUniversos.setVisible(true);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jb_modSerVivoMouseClicked

    private void jb_EliminarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarSerVivoMouseClicked
        //Accion eliminar Ser Vivo
        if (jl_listaUniversos.getSelectedIndex() >= 0) {
            u_seleccionado = listaUniversos.get(jl_listaUniversos.getSelectedIndex());

            String salida_seresVivos = "";
            for (int i = 0; i < u_seleccionado.getLista_seresVivos().size(); i++) {
                salida_seresVivos += "[" + i + "]" + u_seleccionado.getLista_seresVivos().get(i) + "\n";
            }

            try {

                int elim_sv = Integer.parseInt(JOptionPane.showInputDialog(jd_menuUniversos,
                        "Lista de Seres Vivos del Universo " + u_seleccionado.getNombre() + "\n"
                        + salida_seresVivos + "\n"
                        + "Seleccione ser vivo a eliminar: "));

                sv_seleccionado = u_seleccionado.getSerVivo(elim_sv);

                int resp_seguir = JOptionPane.showConfirmDialog(this, "¿Seguro?", "Eliminar Ser Vivo",
                        JOptionPane.YES_NO_OPTION);

                if (resp_seguir == 0) {

                    if (u_seleccionado.getLista_seresVivos().size() == 1) {
                        JOptionPane.showMessageDialog(jd_menuUniversos, "No puede eliminar al unico ser vivo del universo.");
                    } else {
                        //Agregara otro ser
                        u_seleccionado.getLista_seresVivos().remove(elim_sv);
                        if (u_seleccionado.getArchivo() != null) {
                            try {
                                u_seleccionado.escribirArchivo(u_seleccionado.getArchivo().toString());
                            } catch (IOException ex) {

                            }
                        }
                        JOptionPane.showMessageDialog(jd_menuUniversos, "Se elimino el registro del ser vivo exitosamente!!");
                        //Escribir Archivo
                    }

                } else {
                    JOptionPane.showMessageDialog(jd_menuUniversos, "No se elimino el ser Vivo");
                }
            } catch (NullPointerException e) {
                //do nothing

            }

        } else {
            JOptionPane.showMessageDialog(jd_menuUniversos, "Debe elegir un universo.");
        }


    }//GEN-LAST:event_jb_EliminarSerVivoMouseClicked

    private void jb_agregarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarSerVivoMouseClicked
        //Abrir venta crear ser vivo
        //Elegir un universo

        if (cb_universos.getSelectedIndex() > 0) {
            u_seleccionado = listaUniversos.get(cb_universos.getSelectedIndex() - 1);
            ciclo = 1;
            jd_menuUniversos.setVisible(false);
            jd_CrearSerVivo.setModal(true);
            jd_CrearSerVivo.pack();
            jd_CrearSerVivo.setLocationRelativeTo(jd_menuUniversos);
            jd_CrearSerVivo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(jd_menuUniversos, "Debe elegir un universo!!");
        }


    }//GEN-LAST:event_jb_agregarSerVivoMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

        if (jTabbedPane1.getSelectedIndex() == 1 || jTabbedPane1.getSelectedIndex() == 2) {
            if (listaUniversos.isEmpty()) {
                JOptionPane.showMessageDialog(jd_menuUniversos, "Debe crear minimo 1 universo para poder acceder a esta funcion!");
                jTabbedPane1.setSelectedIndex(0);
            }
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanel2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentHidden
        //Accion Reabrir Frame principal

        this.setVisible(true);

    }//GEN-LAST:event_jPanel2ComponentHidden

    private void jb_guardarUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarUniversoMouseClicked
        //Accion Guardar Universo

        if (listaUniversos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ningun universo,\n"
                    + "Debe crear minimo 1 para acceder a esta funcion.");
        } else {
            String salida_universos = "";
            for (int i = 0; i < listaUniversos.size(); i++) {
                salida_universos += "[" + i + "]" + listaUniversos.get(i) + "\n";
            }

            String opcion_universo = JOptionPane.showInputDialog(this, "Lista de Universos\n"
                    + salida_universos + "\n"
                    + "Seleccione universo a guardar: ");

            if (opcion_universo == null) {
                //do nothing
            } else {

                int pos_universo = Integer.parseInt(opcion_universo);
                u_seleccionado = listaUniversos.get(pos_universo);

                if (u_seleccionado.getArchivo() != null) {
                    try {
                        u_seleccionado.escribirArchivo(u_seleccionado.getArchivo().toString());
                        JOptionPane.showMessageDialog(this, "Se guardo exitosamente!!");
                    } catch (IOException ex) {

                    }
                } else {
                    //Escribir Archivo
                    try {

                        JFileChooser jfc = new JFileChooser();

                        jfc.setSelectedFile(new File(u_seleccionado.getNombre() + ".txt"));
                        int seleccion = jfc.showSaveDialog(this);
                        String ubicacion = jfc.getCurrentDirectory().getAbsolutePath();
                        if (seleccion == JFileChooser.APPROVE_OPTION) {
                            jfc.setSelectedFile(u_seleccionado.getArchivo());
                            u_seleccionado.escribirArchivo(ubicacion + "/" + u_seleccionado.getNombre() + ".txt");
                            u_seleccionado.setArchivo(new File(ubicacion + "/" + u_seleccionado.getNombre() + ".txt"));
                            JOptionPane.showMessageDialog(this, "Se guardo exitosamente el universo");
                        } else {
                            JOptionPane.showMessageDialog(this, "No se guardo el universo :(");
                        }
                    } catch (Exception e) {
                    }
                }

            }

        }
    }//GEN-LAST:event_jb_guardarUniversoMouseClicked

    private void jb_regresarMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarMainMouseClicked
        jd_menuUniversos.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jb_regresarMainMouseClicked

    private void jb_cargarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cargarArchivoMouseClicked
        //Accion Cargar Archivo

        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        Scanner sc = null;

        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                Universo u_cargado = new Universo(jfc.getSelectedFile().getName());
                u_cargado.setArchivo(jfc.getSelectedFile());
                
                u_cargado.cargarArchivo(jfc.getSelectedFile().getAbsoluteFile());
                
                //System.out.println(u_cargado.getLista_seresVivos());
                
                String salida = "";
                for (int i = 0; i < u_cargado.getLista_seresVivos().size(); i++) {
                    Seres_Vivos sv = u_cargado.getSerVivo(i);
                    salida +="[" + i + "] " + "Nombre: " + sv.getNombre() + ", Poder: " + sv.getPoder()
                            + ", Años: " + sv.getYears() + ", Planeta: " + sv.getPlaneta_procedencia() + ", Raza:" + sv.getRaza() + "\n";
                }
                ta_Archivos.append("Universo :" + u_cargado.getNombre() + "\n" + salida);
                ta_Archivos.append("\n");
                listaUniversos.add(u_cargado);
                refrescarCBUniversos();
                refrescarListaUniversos();
                JOptionPane.showMessageDialog(this, "Se cargo el archivo exitosamente!!");

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_cargarArchivoMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Lab6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_RazaMod;
    private javax.swing.ButtonGroup bg_RazaSerVivo;
    private javax.swing.JComboBox<String> cb_universos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_CrearSerVivo;
    private javax.swing.JButton jb_EliminarSerVivo;
    private javax.swing.JButton jb_agregarSerVivo;
    private javax.swing.JButton jb_cargarArchivo;
    private javax.swing.JButton jb_crearUniverso;
    private javax.swing.JButton jb_guardarUniverso;
    private javax.swing.JButton jb_menuUniversos;
    private javax.swing.JButton jb_modSerVivo;
    private javax.swing.JButton jb_modificarSerVivo;
    private javax.swing.JButton jb_regresarMain;
    private javax.swing.JDialog jd_CrearSerVivo;
    private javax.swing.JDialog jd_menuUniversos;
    private javax.swing.JDialog jd_modSerVivo;
    private javax.swing.JList<String> jl_listaUniversos;
    private javax.swing.JSpinner js_poderSerVivo;
    private javax.swing.JSpinner js_poderSerVivoMod;
    private javax.swing.JRadioButton rb_Amanto;
    private javax.swing.JRadioButton rb_AmantoMod;
    private javax.swing.JRadioButton rb_Humano;
    private javax.swing.JRadioButton rb_HumanoMod;
    private javax.swing.JTextArea ta_Archivos;
    private javax.swing.JTextField tf_añosSerVivo;
    private javax.swing.JTextField tf_añosSerVivoMod;
    private javax.swing.JTextField tf_nombreSerVivo;
    private javax.swing.JTextField tf_nombreSerVivoMod;
    private javax.swing.JTextField tf_planetaSerVivo;
    private javax.swing.JTextField tf_planetaSerVivoMod;
    // End of variables declaration//GEN-END:variables

    Universo u_seleccionado;
    Seres_Vivos sv_seleccionado;
    ArrayList<Universo> listaUniversos = new ArrayList();
    int ciclo = 0;

    public void refrescarCBUniversos() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        model.addElement("----------");

        for (Universo u : listaUniversos) {
            model.addElement(u);
        }

        cb_universos.setModel(model);

    }

    public void refrescarListaUniversos() {
        DefaultListModel model = new DefaultListModel();

        for (Universo u : listaUniversos) {
            model.addElement(u);
        }

        jl_listaUniversos.setModel(model);

    }
}
